### ISSUE TITLE
host server doesn't listen to 60000 port when run

### ISSUE THREAD

**Issue by zengsamuel** [jeremyczhen/fdbus#2]
when I first run host server, it doesn't listen to 60000 port. 
After I run name server, it starts to listen.
My question is how can I connect my name server from remote if host server doesn't listen?

**Comment by zengsamuel** [comment]
I guess I should start host server and name server in the same machine and then other name server can connect to host server. So I will close it.

**Comment by jeremyczhen** [comment]
Hello,When host server is started, it expects socket address from name server. If name server is not started at the same machine, it does not bind to any address.Once name server is started, it will give TCP and UDS (if applicable) address to host server.
    On Tuesday, July 16, 2019, 6:17:10 PM GMT+8, zengsamuel <notifications@github.com> wrote:  
 
 
Closed #2.
